# Generated by Django 5.0.4 on 2024-04-26 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_citas_remove_profile_username_delete_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.TimeField(default=datetime.time(2, 54, 51, 710861)),
        ),
    ]
