# Generated by Django 5.0.4 on 2024-05-10 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_citas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='servicio',
            field=models.CharField(choices=[('CG', 'Consulta General'), ('OD', 'Odontología'), ('PD', 'Pediatría'), ('CR', 'Cardiología')], default='CG', max_length=2),
        ),
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.TimeField(default=datetime.time(3, 5, 7, 764943)),
        ),
    ]
