# Generated by Django 5.0.4 on 2024-05-10 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_citas_servicio_alter_citas_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.TimeField(default=datetime.time(3, 31, 16, 731537)),
        ),
    ]
